# -*- coding: utf-8 -*-
"""PrakAlgo[7]

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x8q8dlhbw01MtLBNToIWsDWKXv3_DJyg
"""

print('@@@@ @@   @ @@@@@  @@@@  @@@@@@ @       @')
print('@  @ @ @  @ @    @ @   @ @      @       @')
print('@@@@ @  @ @ @    @ @   @ @@@@@@ @   @   @')
print('@  @ @   @@ @    @ @@@@  @      @   @   @')
print('@  @ @    @ @@@@@  @   @ @@@@@@ @@@@@@@@@')
def hitung_faktorial(n):
    if n < 0:
        return "Faktorial tidak dapat dihitung untuk bilangan negatif."
    elif n == 0 or n == 1:
        return 1
    else:
        hasil = 1
        for i in range(2, n + 1):
            hasil *= i
        return hasil
bilangan = int(input("nilai: "))
print(f"Faktorial dari {bilangan} adalah {hitung_faktorial(bilangan)}")

print('@@@@ @@   @ @@@@@  @@@@  @@@@@@ @       @')
print('@  @ @ @  @ @    @ @   @ @      @       @')
print('@@@@ @  @ @ @    @ @   @ @@@@@@ @   @   @')
print('@  @ @   @@ @    @ @@@@  @      @   @   @')
print('@  @ @    @ @@@@@  @   @ @@@@@@ @@@@@@@@@')
def hitung_faktorial(n):
    if n < 0:
        return "Faktorial tidak dapat dihitung untuk bilangan negatif."
    elif n == 0 or n == 1:
        return 1
    else:
        hasil = 1
        for i in range(2, n + 1):
            hasil *= i
        return hasil
bilangan = int(input("nilai: "))
print(f"Faktorial dari {bilangan} adalah {hitung_faktorial(bilangan)}")

print('@@@@ @@   @ @@@@@  @@@@  @@@@@@ @       @')
print('@  @ @ @  @ @    @ @   @ @      @       @')
print('@@@@ @  @ @ @    @ @   @ @@@@@@ @   @   @')
print('@  @ @   @@ @    @ @@@@  @      @   @   @')
print('@  @ @    @ @@@@@  @   @ @@@@@@ @@@@@@@@@')
def hitung_vokal_dan_konsonan(kalimat):
    vokal = 0
    konsonan = 0
    for huruf in kalimat:
        huruf = huruf.lower()
        if huruf in 'aeiou':
            vokal += 1
        elif huruf.isalpha():
            konsonan += 1

    return vokal, konsonan

kalimat = input("Masukkan sesuatu: ")

jml_vokal, jml_konsonan = hitung_vokal_dan_konsonan(kalimat)
print(f"Jumlah huruf Vokal: {jml_vokal}")
print(f"Jumlah huruf konsonan: {jml_konsonan}")

print('@@@@ @@   @ @@@@@  @@@@  @@@@@@ @       @')
print('@  @ @ @  @ @    @ @   @ @      @       @')
print('@@@@ @  @ @ @    @ @   @ @@@@@@ @   @   @')
print('@  @ @   @@ @    @ @@@@  @      @   @   @')
print('@  @ @    @ @@@@@  @   @ @@@@@@ @@@@@@@@@')
def pangkat_kubik(angka):
    return angka ** 3

def cek_pembagian_tiga(angka):
    if angka % 3 == 0:
        return pangkat_kubik(angka)
    else:
        return "False"

# Meminta input dari pengguna
angka = int(input("Masukkan nilai: "))

# Memanggil fungsi cek_pembagian_tiga dan menampilkan hasilnya
hasil = cek_pembagian_tiga(angka)

if hasil != "False":
    print(f"Hasilnya adalah {hasil}")
else:
    print(hasil)